export const calculatorCategories = [
  'Beams',
  'Columns',
  'Connections',
  'Foundations',
  'Loads',
  'Misc',
];

export const calculators = [
  {
    slug: 'composite-section-properties',
    name: 'Composite Steel Beam + Concrete Deck Section Properties',
    description: 'Computes I and section moduli for steel-only and composite transforms (n, 3n, cracked negative).',
    category: 'Beams',
    tags: ['Steel', 'Composite', 'Deck'],
    keywords: ['composite', 'section properties', 'transformed section', 'modular ratio', 'cracked'],
  },
  {
    slug: 'steel-beam-bending-aisc',
    name: 'Steel Beam Bending (AISC)',
    description: 'Check compactness, strength, and demand/capacity for steel beams.',
    category: 'Beams',
    tags: ['AISC', 'Steel'],
    keywords: ['beam', 'bending', 'moment', 'section modulus', 'lrfd'],
  },
  {
    slug: 'steel-beam-deflection',
    name: 'Steel Beam Deflection',
    description: 'Evaluate serviceability deflection for common load and support cases.',
    category: 'Beams',
    tags: ['Steel', 'Serviceability'],
    keywords: ['beam', 'deflection', 'EI', 'serviceability', 'span'],
  },
  {
    slug: 'wood-beam-nds',
    name: 'Wood Beam (NDS)',
    description: 'Compute adjusted design values and beam checks for wood members.',
    category: 'Beams',
    tags: ['NDS', 'Wood'],
    keywords: ['wood', 'beam', 'nds', 'adjustment factors', 'bending'],
  },
  {
    slug: 'column-buckling-aisc',
    name: 'Column Buckling (AISC)',
    description: 'Determine axial compression strength using AISC buckling equations.',
    category: 'Columns',
    tags: ['AISC', 'Steel'],
    keywords: ['column', 'buckling', 'kl/r', 'compression', 'stability'],
  },
  {
    slug: 'base-plate-anchor-rod-tension',
    name: 'Base Plate / Anchor Rod Tension (AISC)',
    description: 'Screen base plate tension demand and anchor rod force distribution.',
    category: 'Connections',
    tags: ['AISC', 'Steel'],
    keywords: ['base plate', 'anchor rod', 'tension', 'connection', 'plate'],
  },
  {
    slug: 'concrete-footing-bearing',
    name: 'Concrete Footing Bearing',
    description: 'Estimate soil bearing pressure and footing contact stress checks.',
    category: 'Foundations',
    tags: ['Concrete', 'Geotechnical'],
    keywords: ['footing', 'bearing', 'soil pressure', 'foundation', 'concrete'],
  },
  {
    slug: 'wind-pressure-asce-7',
    name: 'Wind Pressure (ASCE 7)',
    description: 'Compute velocity pressure and design wind pressure components.',
    category: 'Loads',
    tags: ['ASCE 7', 'Wind'],
    keywords: ['wind', 'pressure', 'asce 7', 'exposure', 'gust'],
  },
  {
    slug: 'tributary-load-taker',
    name: 'Tributary Load Taker',
    description: 'Convert area loads into line and point loads by tributary width.',
    category: 'Misc',
    tags: ['Loads', 'Planning'],
    keywords: ['tributary', 'load', 'area load', 'line load', 'framing'],
  },
];
